#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
