#!/usr/bin/env bash
# Install Nginx and configure a redirection

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "/server_name _;/a location /redirect_me {\\n\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}\\n" /etc/nginx/sites-available/default
service nginx restart
