#!/usr/bin/env bash
#onfigure web-02 to be identical to web-01
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)


apt-get -y update
apt-get -y install nginx
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
