#!/usr/bin/env bash
#Set trap for SIGTERM signals.
trap func SIGTERM

function func(){
	 echo "I am invincible!!!"
}


flag=0
while [ $flag -eq 0 ]
do
        echo "To infinity and beyond indefinitely"
	sleep 2

done
