#!/usr/bin/env bash
# script that gives you information about the school file.
file="Alxschool"
if [ -e "$file" ]
then
    echo "school file exists";
    if [ -s "$file" ]
    then
	echo "school file does not exist";
    else
	echo "school file is not empty";
    fi
    if [ -f "$file" ]
    then
	 echo "school is a regular file";
    fi
else
    echo "school file does not exist";
fi
